document.querySelector(".sorualani").style.display="none";
document.querySelector("#brdr").addEventListener("click", () => {
  document.querySelector("#brdr").style="display: none";
  document.querySelector(".sorualani").style="display: flex; animation: sorualani 1s ease-in-out forwards";
  start();
  document.querySelector(".moon").style="animation: uydu 5s ease-in-out infinite";
  const skan = document.querySelectorAll(".suk");
  skan.forEach((skan) => {
    setTimeout(() => {
      skan.style="opacity: 1";
    }, 350);
  });
});
function start(){
var sorular = [
  "Aşağıdakilerden hangisi volkanik bir dağdır?",
  "Aşağıdakilerden hangisi Dünya'nın en ince katmanıdır?",
  "Manto'nun sona erdiği, 2.900km ile yerin merkezi olan 6.300km arasında yer alan katman hangisidir?",
  "Türkiye'nin başkenti nedir?",
  "Dünyanın en büyük okyanusu hangisidir?",
  "Kuzey Amerika'nın en yüksek dağı nedir?",
  "Güney Amerika'nın en uzun nehri nedir?",
  "Afrika'nın en kalabalık ülkesi hangisidir?",
  "Avrupa'nın en büyük gölü nedir?",
  "Asya'nın en kalabalık ülkesi hangisidir?",
  "Avustralya'nın en büyük şehri nedir?",
  "Antarktika kıtası üzerinde hangi ülke hakimiyet kurmaktadır?",
  "Ekvator çizgisi hangi ülkelerden geçer?",
  "Kuzey Kutbu'nda yer alan deniz nedir?",
  "Dünyanın en derin okyanusu nedir?",
  "Brezilya'nın en büyük şehri nedir?",
  "Kuzey Amerika'da Rocky Dağları'nın diğer adı nedir?",
  "Afrika'nın en yüksek dağı nedir?",
  "Orta Doğu'da yer alan en büyük göl nedir?",
  "Güney Amerika'da en yüksek dağ nedir?",
  "Rusya'nın en uzun nehri nedir?",
  "Çin'in en büyük şehri nedir?",
  "Amerika'nın en büyük gölü nedir?",
  "İtalya'nın en büyük adası nedir?",
  "Fransa'nın en uzun nehri nedir?",
  "Japonya'nın en yüksek dağı nedir?",
  "Hindistan'ın en büyük gölü nedir?",
  "İspanya'nın en yüksek dağı nedir?",
  "Arktik Okyanusu'nun en büyük adası nedir?",
  "Endonezya'nın en kalabalık adası nedir?",
  "Kanada'nın en büyük gölü nedir?",
  "Güney Afrika'nın en büyük şehri nedir?",
  "Arabistan Yarımadası'nın en yüksek dağı nedir?",
  "Avusturya'nın en uzun nehri nedir?",
  "Karadeniz'in en büyük adası nedir?",
  "Kolombiya'nın en büyük şehri nedir?",
  "Asya'nın en yüksek gölü nedir?",
  "Pasifik Okyanusu'ndaki en büyük ada nedir?",
  "Norveç'in en uzun fjordu nedir?",
  "Meksika'nın en büyük gölü nedir?",
  "Gürcistan'ın başkenti nedir?",
  "Hindistan'ın en kalabalık şehri nedir?",
  "Arap Yarımadası'nın en büyük ülkesi nedir?",
  "İsviçre'nin en yüksek dağı nedir?",
  "İrlanda'nın en uzun nehri nedir?",
  "Endonezya'nın en yüksek dağı nedir?",
  "Kuzey Amerika'da Great Plains bölgesi hangi ülkeleri kapsar?",
  "Güney Amerika'nın en büyük gölü nedir?",
  "Avrupa'nın en yüksek dağı nedir?",
  "Asya'nın en büyük nehrinin adı nedir?",
  "Asya kıtasının en doğusunda yer alan ülke nedir?",
  "Avrupa'nın en kalabalık şehri nedir?",
  "Afrika'nın en uzun nehri nedir?",
  "Dünyanın en geniş kanyonu nedir?",
  "Orta Amerika'nın en büyük gölü nedir?",
  "Brezilya'nın en uzun nehri nedir?",
  "Çin Seddi'nin uzunluğu nedir?",
  "Dünyanın en büyük adası nedir?",
  "Rusya'nın en kalabalık şehri nedir?",
  "Amerika'nın en uzun nehri nedir?",
  "Hindistan'ın en büyük limanı hangisidir?",
  "Japonya'nın en büyük adası nedir?",
  "Fransa'nın en yüksek zirvesi nedir?",
  "Avustralya'nın en yüksek dağı nedir?",
  "Endonezya'nın en büyük adası nedir?",
  "Güney Amerika'nın en kalabalık şehri nedir?",
  "Arabistan Yarımadası'nın en büyük şehri nedir?",
  "Gürcistan'ın en büyük gölü nedir?",
  "Norveç'in en büyük şehri nedir?",
  "İspanya'nın en uzun nehri nedir?",
  "Yunanistan'ın en yüksek dağı nedir?",
  "Kanada'nın en uzun nehri nedir?",
  "Arap Yarımadası'nda en büyük göl nedir?",
  "Hindistan'ın en yüksek zirvesi nedir?",
  "Dünyanın en derin gölü nedir?",
  "Brezilya'nın en yüksek zirvesi nedir?",
  "Asya'nın en kalabalık şehri nedir?",
  "Pasifik Okyanusu'ndaki en derin çukurun adı nedir?",
  "Kuzey Amerika'nın en büyük gölü nedir?",
  "Güney Amerika'nın en yüksek zirvesi nedir?",
  "Avrupa'nın en uzun nehri nedir?",
  "Afrika'nın en yüksek zirvesi nedir?",
  "Orta Amerika'nın en yüksek zirvesi nedir?",
  "Rusya'nın en uzun ırmağı nedir?",
  "Asya'nın en büyük adası nedir?",
  "Hindistan'ın en büyük ırmak deltası nedir?",
  "Avustralya'nın en uzun nehri nedir?",
  "Güney Amerika'nın en uzun dağı nedir?",
  "Antarktika'nın en yüksek zirvesi nedir?",
  "Kuzey Amerika'nın en büyük nehir sistemi nedir?",
  "Asya'nın en büyük gölü nedir?",
  "Pasifik Okyanusu'ndaki en büyük adalar hangileridir?",
  "Güney Amerika'nın en büyük nehir sistemi nedir?",
  "Avrupa'nın en yüksek gölü nedir?",
  "Orta Amerika'nın en büyük nehir sistemi nedir?",
  "Rusya'nın en büyük gölü nedir?",
  "Afrika'nın en uzun nehir sistemi nedir?",
  "Asya'nın en uzun nehir sistemi nedir?",
  "Güney Amerika'nın en yüksek gölü nedir?",
  "Avrupa'nın en uzun nehir sistemi nedir?",
  "Orta Amerika'nın en yüksek gölü nedir?",
  "Afrika'nın en büyük gölü nedir?",
  "Rusya'nın en uzun nehir sistemi nedir?",
  "Pasifik Okyanusu'ndaki en derin çukurun derinliği nedir?",
  "Asya'nın en yüksek zirvesi nedir?",
  "Antarktika'daki en büyük buz tabakasının adı nedir?",
  "Avrupa'nın en yüksek zirvesi nedir?",
  "Pasifik Okyanusu'ndaki en büyük ada nedir?",
  "Güney Amerika'nın en büyük gölü nedir?",
  "Orta Amerika'daki en büyük göl nedir?",
  "Afrika'daki en büyük göl nedir?",
  "Asya'daki en büyük göl nedir?",
  "Avrupa'daki en büyük göl nedir?",
  "Güney Amerika'daki en büyük nehir nedir?",
  "Orta Amerika'daki en büyük nehir nedir?",
  "Afrika'daki en büyük nehir nedir?",
  "Asya'daki en büyük nehir nedir?",
  "Avrupa'daki en uzun nehir nedir?",
  "Güney Amerika'daki en uzun nehir nedir?",
  "Orta Amerika'daki en uzun nehir nedir?",
  "Afrika'daki en uzun nehir nedir?",
  "Asya'daki en uzun nehir nedir?",
  "Pasifik Okyanusu'ndaki en derin çukurun adı nedir?",
  "Antarktika'daki en yüksek zirve nedir?",
  "Avrupa'daki en yüksek zirve nedir?",
  "Asya'daki en yüksek zirve nedir?",
  "Pasifik Okyanusu'ndaki en yüksek zirve nedir?",
  "Kuzey Amerika'daki en yüksek zirve nedir?",
  "Orta Amerika'daki en yüksek zirve nedir?",
  "Güney Amerika'daki en yüksek zirve nedir?",
  "Afrika'daki en yüksek zirve nedir?",
  "Avustralya'daki en yüksek zirve nedir?"
];

var siklar = [
  "Ağrı Dağı",
  "Yer Kabuğu",
  "Çekirdek",
  "Stratosfer",
  "Ankara",
  "Pasifik Okyanusu",
  "Denali",
  "Amazon Nehri",
  "Nijerya",
  "Ladoga Gölü",
  "Çin",
  "Sydney",
  "Hiçbir ülkenin, Antarktika Antlaşması uyarınca hakimiyeti yoktur.",
  "Ekvador, Kolombiya ve Brezilya",
  "Kara Deniz",
  "Pasifik Okyanusu",
  "São Paulo",
  "Kaya Dağları",
  "Kilimanjaro",
  "Van Gölü",
  "Aconcagua",
  "Lena Nehri",
  "Şangay",
  "Süperior Gölü",
  "Sicilya",
  "Rhone Nehri",
  "Fuji Dağı",
  "Vembanad Gölü",
  "Teide Dağı",
  "Grönland",
  "Java",
  "Süperior Gölü",
  "Johannesburg",
  "Cebelitarık Dağı",
  "Donau (Tuna)",
  "Kırım",
  "Bogotá",
  "Nam Tso",
  "Greenland",
  "Lake Victoria",
  "Valletta",
  "Sen Nehri",
  "Grand Canyon",
  "Nicaragua Gölü",
  "Amazon Nehri",
  "21.196 km",
  "Grönland",
  "Moskova",
  "Mississippi Nehri",
  "Mumbai Limanı",
  "Honshu",
  "Mont Blanc",
  "Kosciuszko Dağı",
  "Sumatra",
  "Karaib Adaları",
  "Buenos Aires",
  "Riyadh",
  "Batı Gölü",
  "Oslo",
  "Ebro Nehri",
  "Olympus Dağı",
  "Yushan",
  "Montreal",
  "Caddo Gölü",
  "Newfoundland",
  "Meksiko Nehri",
  "Tiflis",
  "Mumbai",
  "Suudi Arabistan",
  "Großglockner",
  "Shannon Nehri",
  "Puncak Jaya",
  "Kuzey Amerika'nın Orta Batısı",
  "Maracaibo Gölü",
  "Elbruz Dağı",
  "Yangtze Nehri",
  "Çin",
  "İstanbul",
  "Nil Nehri",
  "Canyon Diablo",
  "Managua Gölü",
  "Parana Nehri",
  "Ganges Nehri",
  "Denali",
  "Antarktika Buz Tabakası",
  "Mont Blanc",
  "Hawaii Adaları",
  "Titicaca Gölü",
  "Urmiye Gölü",
  "Nil Nehri",
  "Colorado Nehri",
  "Ön Hint Adaları",
  "Baffin Adası",
  "Andaman ve Nikobar Adaları",
  "Öncüldür Gölü",
  "Kahire",
  "Arktik Okyanusu'nun Mendlöp Kuyruğu",
  "Süperior Gölü",
  "Aconcagua",
  "Volga Nehri",
  "Süperior Gölü",
  "Nevado Mismi",
  "Süperior Gölü",
  "Süperior Gölü",
  "Süperior Gölü",
  "Süperior Gölü",
  "Colorado Çukuru",
  "Everest",
  "Bentley Çukuru",
  "Süperior Gölü",
  "Aconcagua",
  "Donau (Tuna)",
  "Kilimanjaro",
  "Rize",
  "Süperior Gölü",
  "Süperior Gölü",
  "Süperior Gölü",
  "Süperior Gölü",
  "Süperior Gölü",
  "Mariana Çukuru",
  "Vinson Massif",
  "Mont Blanc",
  "Everest",
  "Mauna Kea"];
  
var sahtesiklar = [
  "Ankara", "İzmir", "Bursa", "Adana",
  "Atlantik Okyanusu", "Hint Okyanusu", "Büyük Okyanus", "Akdeniz",
  "Everest Dağı", "K2 Dağı", "Mont Blanc", "Denali Dağı",
  "Amazon Nehri", "Mississippi Nehri", "Nijer Nehri", "Yangtze Nehri",
  "Nijerya", "Gana", "Kenya", "Fas",
  "Ladoga Gölü", "Baikal Gölü", "Issyk-Kul Gölü", "Tuz Gölü",
  "Çin", "Hindistan", "Rusya", "ABD",
  "Sydney", "Melbourne", "Tokyo", "New York",
  "Antarktika Yarımadası", "Arktik Kıyısı", "Grönland", "Svalbard",
  "Ekvador, Kolombiya ve Brezilya", "Peru, Kolombiya ve Bolivya", "Bolivya, Brezilya ve Paraguay", "Venezuela, Kolombiya ve Guyana",
  "Kara Deniz", "Akdeniz", "Marmara Denizi", "Kızıldeniz",
  "Pasifik Okyanusu", "Hint Okyanusu", "Arktik Okyanusu", "Güney Okyanusu",
  "São Paulo", "Rio de Janeiro", "Brasília", "Belo Horizonte",
  "Kaya Dağları", "Appalachian Dağları", "And Dağları", "Himalaya Dağları",
  "Kilimanjaro", "Aconcagua", "Mount Elbrus", "Mount McKinley",
  "Van Gölü", "Beyşehir Gölü", "Eğirdir Gölü", "Gölcük Gölü",
  "Lena Nehri", "Amur Nehri", "Yenisey Nehri", "Ob Nehri",
  "Şangay", "Pekin", "Guangzhou", "Shenzhen",
  "Süperior Gölü", "Michigan Gölü", "Victoria Gölü", "Huron Gölü",
  "Sicilya", "Sardinya", "Korsika", "Kıbrıs",
  "Rhone Nehri", "Loire Nehri", "Tiber Nehri", "Dinyeper Nehri",
  "Fuji Dağı", "Hakusan Dağı", "Tateyama Dağı", "Ontake Dağı",
  "Vembanad Gölü", "Chilika Gölü", "Dal Gölü", "Wular Gölü",
  "Teide Dağı", "Pico Aneto", "Mulhacén", "Monte Perdido",
  "Grönland", "Antarktika", "İzlanda", "Svalbard",
  "Java", "Borneo", "Sumatra", "Sulawesi",
  "Süperior Gölü", "Michigan Gölü", "Huron Gölü", "Erie Gölü",
  "Johannesburg", "Cape Town", "Durban", "Pretoria",
  "Cebelitarık Dağı", "Cebelitarık Boğazı", "Cebelitarık Yarımadası", "Cebelitarık Şehri",
  "Donau (Tuna)", "Volga Nehri", "Rhein Nehri", "Po Nehri",
  "Kırım", "Sicilya", "Sardinia", "Corsica",
  "Bogotá", "Medellín", "Cali", "Barranquilla",
  "Nam Tso", "Qinghai Gölü", "Dangra Gölü", "Rakshastal",
  "Greenland", "Iceland", "Newfoundland", "Svalbard",
  "Lake Victoria", "Lake Tanganyika", "Lake Malawi", "Lake Turkana",
  "Valletta", "Rome", "Athens", "Lisbon",
  "Sen Nehri", "Gambia Nehri", "Niger Nehri", "Blue Nile Nehri",
  "Grand Canyon", "Yellowstone Canyon", "Bryce Canyon", "Zion Canyon",
  "Nicaragua Gölü", "Managua Gölü", "Atitlán Gölü", "Yojoa Gölü",
  "Amazon Nehri", "Orinoco Nehri", "Paraná Nehri", "Magdalena Nehri",
  "21.196 km", "15.000 km", "25.000 km", "18.000 km",
  "Borneo", "Sumatra", "Celebes", "Java",
  "St. Petersburg", "Moscow", "Kazan", "Yekaterinburg",
  "Amazon Nehri", "Nile Nehri", "Yangtze Nehri", "Mississippi Nehri",
  "Mumbai Limanı", "Chennai Limanı", "Kolkata Limanı", "Visakhapatnam Limanı",
  "Honshu", "Kyushu", "Shikoku", "Hokkaido",
  "Mont Blanc", "Matterhorn", "Jungfrau", "Eiger",
  "Kosciuszko Dağı", "Bogong Dağı", "Twynam Dağı", "Seaman Dağı",
  "Sumatra", "Java", "Borneo", "Celebes",
  "Karaib Adaları", "Bahamalar", "Cayman Adaları", "Puerto Rico",
  "Buenos Aires", "Santiago", "Lima", "Bogotá",
  "Riyadh", "Dubai", "Doha", "Muscat",
  "Batı Gölü", "Van Gölü", "Urmia Gölü", "Sevan Gölü",
  "Oslo", "Stockholm", "Helsinki", "Copenhagen",
  "Ebro Nehri", "Tagus Nehri", "Seine Nehri", "Rhine Nehri",
  "Olympus Dağı", "Parnassus Dağı", "Taygetos Dağı", "Pelion Dağı",
  "Yushan", "Jade Dağı", "Hehuan Dağı", "Xueshan",
  "Toronto", "Montreal", "Vancouver", "Calgary",
  "Kahuku Gölü", "Waialua Gölü", "Kawainui Gölü", "Halulu Gölü",
  "Açores", "Madeira", "Canary Adaları", "Azores",
  "Kolorado Nehri", "Missouri Nehri", "Arkansas Nehri", "Columbia Nehri",
  "Bakü", "Tbilisi", "Yerevan", "Bishkek",
  "Delhi", "Mumbai", "Bangalore", "Kolkata",
  "Bahreyn", "Qatar", "Oman", "Kuwait",
  "Triglav", "Velenje", "Kocbek", "Peca",
  "Yukon Nehri", "Mackenzie Nehri", "Liard Nehri", "Porcupine Nehri",
  "Dnieper Nehri", "Don Nehri", "Volga Nehri", "Amur Nehri",
  "Svityaz Gölü", "Synevyr Gölü", "Nesamovyte Gölü", "Molochnoye Gölü",
  "Yangshuo Dağı", "Huangshan Dağı", "Zhangjiajie Dağı", "Emei Dağı",
  "Pirene Dağları", "Cantabrian Dağları", "Asturian Dağları", "Iberian Dağları",
  "Hawa Dağı", "Maui Dağı", "Kilauea Dağı", "Lo'ihi Dağı",
  "Puncak Trikora", "Puncak Mandala", "Puncak Jaya", "Puncak Meren"
];
var yzlnsk;
var yzlnskkldr;
var yzlncvp;
var yzlncvpkldr;
var dogrucvpsikki = [document.querySelectorAll(".cevap")[0], document.querySelectorAll(".cevap")[1], document.querySelectorAll(".cevap")[2], document.querySelectorAll(".cevap")[3], document.querySelectorAll(".cevap")[4]]; 
var soru = sorular[Math.floor(Math.random() * sorular.length)];
document.querySelector("#sorubaslik").innerHTML=soru;
var sorukonumu = sorular.indexOf(soru);
var dogrucvp = dogrucvp.indexOf(sorukonumu);
dogrucvp.innerHTML=dogrucvp;
var sorusiklari = siklar.indexOf(sorukonumu);
var suk;
dogrucvpsikki.forEach((dogrucvpsikki) => {
  suk = sahtesiklar.indexOf(sorukonumu);
  dogrucvpsikki.innerHTML = suk;
  yzlnsk = sahtesiklar.indexOf(suk);
  yzlnskkldr = sahtesiklar.splice(yzlnsk, 1);
  sorukonumu++;
  console.log(yzlnskkldr);
  console.log(yzlnsk);
});
}
